version: '3'
services: 
    mongodb:
        image: mongo:4.4
        ports: 
            - 0.0.0.0:27017:27017
        networks:
            - app-network
    
    event-bus:
        build: "./event-bus"
        ports: 
            - "4005:4005"
        networks:
            - app-network
        volumes: 
            - ./event-bus:/app

    posts:
        build: "./posts"
        ports: 
            - "4000:4000"
        networks:
            - app-network
        volumes: 
            - ./posts:/app
    
    comments:
        build: "./comments"
        ports: 
            - "4001:4001"
        networks:
            - app-network
        volumes: 
            - ./comments:/app

    moderation: 
        build: "./moderation"
        ports: 
            - "4003:4003"
        networks:
            - app-network
        volumes: 
            - ./moderation:/app
    
    query:
        build: "./query"
        ports: 
            - "4002:4002"
        networks:
            - app-network
        volumes: 
            - ./query:/app
    
    auth:
        build: "./auth"
        environment: 
            JWT_KEY: "asdf"
        ports: 
            - "4009:4009"
        networks:
            - app-network
        volumes: 
            - ./auth:/app
        depends_on:
            - mongodb 
    client:
        build: "./client"
        ports: 
            - "80:80"
        networks:
            - app-network
        volumes: 
            - ./client:/app
networks: 
    app-network:
        driver: bridge
