version: '3.8'
services: 
    mongodb:
        image: mongo
        restart: always
        ports: 
            - "27017:27017"
        networks:
            - app-network
    
    event-bus:
        image: azax25547/event-bus
        restart: unless-stopped
        ports: 
            - "4005:4005"
        networks:
            - app-network

    posts:
        image: azax25547/posts
        restart: unless-stopped
        ports: 
            - "4000:4000"
        networks:
            - app-network
    
    comments:
        image: azax25547/comments
        restart: unless-stopped
        ports: 
            - "4001:4001"
        networks:
            - app-network
    moderation: 
        image: azax25547/moderation
        restart: unless-stopped
        ports: 
            - "4003:4003"
        networks:
            - app-network
    
    query:
        image: azax25547/query
        restart: unless-stopped
        ports: 
            - "4002:4002"
        networks:
            - app-network
    
    auth:
        image: azax25547/auth
        restart: unless-stopped
        environment: 
            JWT_KEY: "asdf"
        ports: 
            - "4009:4009"
        
        networks:
            - app-network
    client:
        image: azax25547/client
        restart: unless-stopped
        ports: 
            - "3000:80"
        networks:
            - app-network
networks: 
    app-network:
        driver: bridge
